version: '3'
services:

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  pub-relay:
    build: .
    image: atsu1125/pub-relay:latest
    restart: always
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:8085:8085"
    depends_on:
      - redis
    volumes:
      - ./.env:/relay/.env:ro
      - ./actor.pem:/relay/actor.pem:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:8085/stats || exit 1"]

networks:
  external_network:
  internal_network:
    internal: true
